services:
  - type: web
    name: itmanagementsystem
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn inventory_management.wsgi:application --bind 0.0.0.0:$PORT
